version: '3'

services:
  lineameteo-prometheus:
    build: .
    restart: unless-stopped
    ports:
      - "0.0.0.0:9199:3000"
    environment:
      - HTTP_LISTEN_ADDR=0.0.0.0:3000
      - WANTED_LOCATION_IDS=2166
